### ISSUE TITLE
Download animation from BlinkyTape

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#10]
We can read memory back from the BlinkyTape, so it would be a nice trick to download an animation from a BlinkyTape for further editing.

**Comment by broox** [comment]
+1

**Comment by broox** [comment]
i haven't saved a pattern onto my blinky tape because i want to download the original rainbow pattern it came with first.

**Comment by broox** [comment]
but i now see you can revert to that using patterpaint in `Tools > Restore Rainbow Sketch`.

**Comment by cibomahto** [comment]
Closing, obsolete
