### ISSUE TITLE
OS X: In release mode, clicking the + button to add a new animation doesn't do anything

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#138]
to reproduce:
1. compile pattern paint in release mode
2. run and click the '+' button on the toolbar
3. nothing shows
expected behavior: a menu pops up to add either a frame-based or scrolling pattern

Note: moving the mouse over where the menu should be generates the warning message:
warning unknown: QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)

**Comment by cibomahto** [comment]
Note that this functions correctly in debug mode. A quick google search shows that it might be a message timing bug

**Comment by cibomahto** [comment]
Doesn't affect Win7+Qt5.5.1

**Comment by cibomahto** [comment]
Doesn't affect OS X 10.10.5+Qt5.5.1, suspect a Qt5.4.1 bug

**Comment by cibomahto** [comment]
More fun: a build of 2.0.2 from last week doesn't show this either, from Qt 5.4.1 and OS X 10.10.5. Maybe an XCode issue?

**Comment by cibomahto** [comment]
Hmm, this only seems to be an issue when building through Qt Creator- builds from the release script work fine. Deferring this for now.

Note: Other issues associated with this are that the 'about' and 'system information' windows don't show themselves correctly when selected. Perhaps there is a different issue somewhere that is preventing the signals from being dispatched correctly.

**Comment by luzpaz** [comment]
do you mind leaving a notation on https://bugreports.qt.io/browse/QTBUG-42846 so Qt devs fix it ?

**Comment by cibomahto** [comment]
I'll try to summarize it for there. I never did figure out why I was getting different results when building through Qt Creator vs building through a release script, though, so it might not be very helpful.

For my notes:
-Issue occurs when PatternPaint run in release mode through both Qt Creator 3.3.1 (Qt 5.4.1) and Qt Creator 3.5.1 (Qt 5.5.1) on OS X
-Issue does not occur when run in debug mode through either version.
-Issue does not occur when built outside of Qt Creator, using Qt 5.4.1 directly

**Comment by cibomahto** [comment]
Not reproducible with Qt5.7 and macOs 10.12.1
