### ISSUE TITLE
OS X 10.11.2: Interacting with frameeditor scroll bar gives warning messages

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#139]
To reproduce:
1. compile on Qt 5.4.1 and OS X 10.11.2 (release or debug ok)
2. Run patternpaint
3. select the blinkytile option
4. select the color pattern (since it is the longest), then click and drag the scroll bar on the frameeditor (using the scroll gesture does not cause the problem)
5. warning messages are generated in application output window
expected result: no warnings generated

Note that this does not occur on OS X 10.10.5

2015-12-24 12:27:21.569 PatternPaint[4445:320649] inOptions: {
    "is.flipped" = 1;
    kCUIPartMaskKey = 255;
    kCUIThumbProportionKey = "0.839546191247974";
    noindicator = 1;
    pressedpart = 4;
    state = pressed;
    value = "0.494949494949495";
    widget = scrollbar;
}
2015-12-24 12:27:21.569 PatternPaint[4445:320649] outHitPart = -1
2015-12-24 12:27:21.569 PatternPaint[4445:320649] inOptions: {
    "is.flipped" = 1;
    kCUIPartMaskKey = 768;
    kCUIThumbProportionKey = "0.05025710682060736";
    state = normal;
    value = "0.1446521605884156";
    widget = scrollbar;
}
2015-12-24 12:27:21.570 PatternPaint[4445:320649] inOptions: {
    "is.flipped" = 1;
    kCUIPartMaskKey = 768;
    kCUIThumbProportionKey = "0.05025710682060736";
    state = normal;
    value = "0.1446521605884156";
    widget = scrollbar;
}
2015-12-24 12:27:21.570 PatternPaint[4445:320649] outHitPart = -1

**Comment by macszur-mob** [comment]
Hello,

I found this page while I was looking for some infos about exactly the same warning in my Java Swing app which is completely different app but also using scrollbars. It only occurs when I press scrollbar - scrolling with mouse/trackpad is fine so maybe it's an os bug ?

**Comment by cibomahto** [comment]
It's possible, though since we are both using widgets that wrap the OS functionality, I'd bet it is more a change in the underlying API that exposed some weirdness in the wrapper (or just exposed some problem with the way I'm using it). If I find out anything more I'll report it here.

**Comment by swpease** [comment]
I was getting the same error with scroll bars. I was using Qt 5.5.0 and OS X 10.11.2. I just updated to OS X 10.11.5 and that seems to have fixed it.

**Comment by cibomahto** [comment]
Not reproducible with Qt5.7 and 10.12.1
