### ISSUE TITLE
Please provide basic files for Linux

### ISSUE THREAD

**Issue by probonopd** [Blinkinlabs/PatternPaint#153]
Please provide `patternpaint.desktop` for Linux so that PatternPaint can be integrated into the menu.

For example:

```
[Desktop Entry]
Name=PatternPaint
Type=Application
Icon=patternpaint
Exec=PatternPaint
Categories=Development;
Comment=Making beautiful light shows is as easy as drawing a picture
```

Also, it would be nice if "make install" would do something...

**Comment by cibomahto** [comment]
Certainly! Is the png still needed, and if so, what resolution? Could also do svg if that's appropriate.

**Comment by probonopd** [comment]
The pngs are not needed any more, they are now being generated on-the-fly from the `.icns`.
