### ISSUE TITLE
Linux: some image assets missing from appimage build

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#155]
The Welcome Screen images are missing from the linux app image:
![virtualbox_linux mint 17 mate_21_11_2016_11_22_15](https://cloud.githubusercontent.com/assets/44493/20468768/59dc57de-afdd-11e6-8b30-1cd5007f092c.png)
For reference, this is what it should look like:
![screen shot 2016-11-21 at 11 23 16 am](https://cloud.githubusercontent.com/assets/44493/20468767/585916f4-afdd-11e6-89dc-3c67f8812854.png)

**Comment by probonopd** [comment]
Should be a matter of copying the assets to the correct place... let me know if you'd like help from my side on this.

**Comment by probonopd** [comment]
How do you call these images in the code, in other words, where are they expected to be loaded from?

**Comment by cibomahto** [comment]
They are loaded from QUrl addresses during runtime, like this:

https://github.com/Blinkinlabs/PatternPaint/blob/master/PatternPaint/gui/scenetemplate.cpp
SceneTemplate sceneTemplates[SCENE_TEMPLATE_COUNT] = {
    {
        "BlinkyTape",
        ":/scenetemplates/images/scenetemplates/blinkytape.jpg",
        ":/examples/blinkytape",
        "BlinkyTape",
        "Linear",
        RGB,
        60,
        1
},

https://github.com/Blinkinlabs/PatternPaint/blob/master/PatternPaint/gui/welcomescreen.cpp
    for (int i = 0; i < SCENE_TEMPLATE_COUNT; i++) {
        QListWidgetItem *item = new QListWidgetItem(sceneTemplates[i].name, ui->SceneList);
        item->setIcon(QIcon(sceneTemplates[i].photo));
    }

and they are listed in a qrc file:
https://github.com/Blinkinlabs/PatternPaint/blob/master/PatternPaint/images.qrc
https://github.com/Blinkinlabs/PatternPaint/tree/master/PatternPaint/images/scenetemplates

**Comment by probonopd** [comment]
The `:` in the example above means that `QDir::searchPaths` is used. I am not entirely sure how this translates into filesystem search paths.

**Comment by cibomahto** [comment]
I expected them to be embedded in the executable, as that's how they are built on Windows and macOs. Following:
https://doc.qt.io/qt-5/resources.html

I can see that they are pulled into a temp file 'qrc_images.cpp', at least during a normal qmake build on our internal CI server. It's a little interesting that the program icons and other resources should be using the same loading method, but seem to be present in the build.

**Comment by probonopd** [comment]
I can confirm that I have identified the root cause and fixed it in https://github.com/probonopd/linuxdeployqt/commit/4951fd133b43e475d1bd64f32b9c5e265253485b (`} else {` was missing there).

Here is a working AppImage:
https://transfer.sh/JMRDB/patternpaint-git2.0.4-50-g6754f12-x86-64.appimage
Build log:
https://travis-ci.org/probonopd/PatternPaint#L1163

I will send a PR once some cleanup on my side is done.
