### ISSUE TITLE
Too many Qt packages installed for Travis CI builds

### ISSUE THREAD

**Issue by probonopd** [Blinkinlabs/PatternPaint#159]
In `.travis.yml`, `qt57[QTPACKAGE]` is used. This leads to unnecessary stuff like Qt Creator being downloaded on each build, producing waste and longer build times. Can the packages to be installed be reduced to the required minimum?

**Comment by cibomahto** [comment]
Done in 51732baa4f5cecc0d31b178efbe755a7c246f40c.
For reference, only qt57base was needed for compilation. qt57declarative was needed for qmlimportscanner
