### ISSUE TITLE
Drawing grid misaligned

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#169]
The drawing grid is misaligned with the image in recent builds of PatternPaint, so clicking on anything other than the top left of a pixel causes it to paint a surrounding pixel instead of the intended one

![cursor grid](https://cloud.githubusercontent.com/assets/44493/21576767/7760c394-cf77-11e6-82eb-4ff1611856cb.PNG)

Probably introduced here (need to verify):
https://github.com/Blinkinlabs/PatternPaint/commit/6a2f0a92d72a4772d25cf1d19259b7fbd6d8ee37

**Comment by nightflyer88** [comment]
Fixed errors with cursor grid, but are the rectangles still incorrectly drawn?

<img width="1372" alt="bildschirmfoto 2017-01-28 um 21 29 12" src="https://cloud.githubusercontent.com/assets/25297444/22399636/3500e368-e5a1-11e6-9d43-25145f060208.png">

**Comment by cibomahto** [comment]
Thanks! Pulled in your fix:
https://github.com/Blinkinlabs/PatternPaint/commit/befbaf04b748a3bbfde2012d05eced3a9380fcfe

And yeah, looks like the drawing grid is still misaligned with the actual image >.<. It's closer than before.
