### ISSUE TITLE
Travis CI Builds fail, don't find libblinky

### ISSUE THREAD

**Issue by probonopd** [Blinkinlabs/PatternPaint#172]
As we can see from the [Travis CI build log](https://travis-ci.org/Blinkinlabs/PatternPaint/builds/189517985#L533-L538), ` -L../libblinky/release/ -llibblinky` does not seem to do its job and compilation fails with `/usr/bin/ld: cannot find -llibblinky`.

I suspect this has to do with https://github.com/Blinkinlabs/PatternPaint/commit/0e3a57583a3179ad727c7e7b1f9bef53ba1532e7.

Since the application cannot be compiled, the AppImage also does not get generated. https://github.com/Blinkinlabs/PatternPaint/commit/ad2600d562a0d96a6b25651a8629c8ce45bc8cb4 does not help since this is not an issue of `linuxdeployqt` not finding the library, but an issue of the compiler not finding the library during compilation of the application.

Can you build using this configuration on a local machine? Unfortunately I don't know what needs to be changed so that the compiler will find libblinky.

**Comment by cibomahto** [comment]
Thanks for looking into this! We had some big problems with this, and rushed in the testing branch :-/.

I'm not convinced that the app is failing to build- it looks like it is building the binary with no issue:
https://travis-ci.org/Blinkinlabs/PatternPaint/builds/192101493#L548

588: g++ -Wl,-O1 -Wl,-rpath,/opt/qt57/lib -o PatternPaint .tmp/mainwindow.o .tmp/systeminformation.o .tmp/aboutpatternpaint.o .tmp/letterboxscrollarea.o .tmp/colorchooser.o .tmp/patterncollectionmodel.o .tmp/patterncollectiondelegate.o .tmp/patterncollection.o .tmp/frameeditor.o .tmp/patterndelegate.o .tmp/welcomescreen.o .tmp/preferences.o .tmp/sceneconfiguration.o .tmp/scenetemplate.o .tmp/patternframelistview.o .tmp/eventratelimiter.o .tmp/outputpreview.o .tmp/main.o .tmp/abstractinstrument.o .tmp/pencilinstrument.o .tmp/lineinstrument.o .tmp/colorpickerinstrument.o .tmp/sprayinstrument.o .tmp/fillinstrument.o .tmp/autoupdater.o .tmp/qrc_images.o .tmp/qrc_examples.o .tmp/moc_mainwindow.o .tmp/moc_systeminformation.o .tmp/moc_aboutpatternpaint.o .tmp/moc_colorchooser.o .tmp/moc_patterncollectionmodel.o .tmp/moc_patterncollectiondelegate.o .tmp/moc_frameeditor.o .tmp/moc_patterndelegate.o .tmp/moc_welcomescreen.o .tmp/moc_preferences.o .tmp/moc_sceneconfiguration.o .tmp/moc_outputpreview.o .tmp/moc_abstractinstrument.o .tmp/moc_pencilinstrument.o .tmp/moc_lineinstrument.o .tmp/moc_colorpickerinstrument.o .tmp/moc_sprayinstrument.o .tmp/moc_fillinstrument.o   -lusb-1.0 -L/home/travis/build/Blinkinlabs/PatternPaint/src/app/../libblinky/ -llibblinky -L/opt/qt57/lib -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Core -lGL -lpthread 
make[1]: Leaving directory `/home/travis/build/Blinkinlabs/PatternPaint/src/app'

And also, the test binary compiles, and can run during the test if the library path is set manually:
0.03s$ LD_LIBRARY_PATH=./libblinky libblinky-test/libblinky-test

It might be worth noting that macdeployqt also fails to find the library during deployment, however the app runs fine when invoked through Qt Creator on Linux, macOS, and Windows. I'm not actually sure how to set this up correctly. For my Windows build (that lacks a nice deploy tool), I'm manually copying in the .dll file and it's able to run with no trouble.

**Comment by probonopd** [comment]
Indeed, in that build it building. But then, the library is in a location where ldd can't pick it up:
https://travis-ci.org/Blinkinlabs/PatternPaint/builds/192101493#L722

Something along the lines of `sudo cp src/libblinky/liblibblinky.so* /usr/lib/` before running `linuxdeployqt` might do the trick. It uses ldd internally to find the libs.

**Comment by cibomahto** [comment]
Makes sense. The only bit that seems strange to me is that somehow it can work from the build flow in Qt Creator, but then doesn't work when run externally through qmake. I guess that's a good starting point for tracking down the problem.

**Comment by cibomahto** [comment]
And indeed, it's taking a different path. Qt Creator is building the project like this:

22:27:15: Running steps for project PatternPaint...
22:27:15: Starting: "/home/matt/Qt5.7.1/5.7/gcc_64/bin/qmake" /home/matt/Blinkinlabs-Repos/PatternPaint/src/PatternPaint.pro -spec linux-g++
Info: creating stash file /home/matt/Blinkinlabs-Repos/PatternPaint/build-PatternPaint-Desktop_Qt_5_7_1_GCC_64bit-Release/.qmake.stash
22:27:15: The process "/home/matt/Qt5.7.1/5.7/gcc_64/bin/qmake" exited normally.
22:27:15: Starting: "/usr/bin/make" qmake_all
cd libblinky/ && /home/matt/Qt5.7.1/5.7/gcc_64/bin/qmake /home/matt/Blinkinlabs-Repos/PatternPaint/src/libblinky/libblinky.pro -spec linux-g++ -o Makefile
cd libblinky/ && /usr/bin/make -f Makefile qmake_all
make[1]: Entering directory '/home/matt/Blinkinlabs-Repos/PatternPaint/build-PatternPaint-Desktop_Qt_5_7_1_GCC_64bit-Release/libblinky'
make[1]: Nothing to be done for 'qmake_all'.
make[1]: Leaving directory '/home/matt/Blinkinlabs-Repos/PatternPaint/build-PatternPaint-Desktop_Qt_5_7_1_GCC_64bit-Release/libblinky'
cd libblinky-test/ && /home/matt/Qt5.7.1/5.7/gcc_64/bin/qmake /home/matt/Blinkinlabs-Repos/PatternPaint/src/libblinky-test/libblinky-test.pro -spec linux-g++ -o Makefile
Project WARNING: outside pri:
Project WARNING: /home/matt/Blinkinlabs-Repos/PatternPaint/src/libblinky-test
Project WARNING: /home/matt/Blinkinlabs-Repos/PatternPaint/build-PatternPaint-Desktop_Qt_5_7_1_GCC_64bit-Release/libblinky-test
cd libblinky-test/ && /usr/bin/make -f Makefile qmake_all

while the travis build looks more like this:
https://travis-ci.org/Blinkinlabs/PatternPaint#L371

0.00s$ cd src
The command "cd src" exited with 0.
0.11s$ qmake -config release
Info: creating stash file /home/travis/build/Blinkinlabs/PatternPaint/src/.qmake.stash
The command "qmake -config release" exited with 0.
91.92s$ make -j7
cd libblinky/ && ( test -e Makefile || /opt/qt57/bin/qmake

**Comment by cibomahto** [comment]
In the Qt Creator launch settings, I found this- must be how it's working there.
![build library search path](https://cloud.githubusercontent.com/assets/44493/21963441/bfdbf634-db75-11e6-8ee2-77abace59339.PNG)

**Comment by probonopd** [comment]
Yes, that must be it! Thanks for sharing.

**Comment by cibomahto** [comment]
For now, adding the library to LD_LIBRARY_PATH allows the build to pass:
https://github.com/Blinkinlabs/PatternPaint/blob/master/dist_linux.sh#L62-L63

```
# TODO: this should be done automatically through the qt build tools?
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:libblinky/release

${LINUXDEPLOYQT} app/release/PatternPaint -verbose=2 -bundle-non-qt-libs
${LINUXDEPLOYQT} app/release/PatternPaint -verbose=2 -appimage
```

**Comment by cibomahto** [comment]
And also note that I pulled all of the actual build commands out of the .travis.yml file, both to make it easier to test locally, and also so it will work with our Jenkins machine ;-)

**Comment by cibomahto** [comment]
Putting it in LD_LIBRARY_PATH allows the deployment tool to complete successfully, but produces an appimage that is missing the library:
https://transfer.sh/gfQF6/patternpaint-git2.1.2-29-gdc81ab5-x86-64.appimage

```
./patternpaint-git2.1.2-29-gdc81ab5-x86-64.appimage 
./patternpaint-git2.1.2-29-gdc81ab5-x86-64.appimage: error while loading shared libraries: libblinky.so.1: cannot open shared object file: No such file or directory

```
So maybe that's not the right path to take.

The next attempt was to copy it in manually:
https://github.com/Blinkinlabs/PatternPaint/blob/master/dist_linux.sh#L59-L61

```
# TODO: this should be done automagically though the qt build tools?
mkdir -p app/release/lib
cp libblinky/release/libblinky.so.1 app/release/lib
```

Copying it manually gets a slightly different outcome:
https://transfer.sh/Bx4Ti/patternpaint-git2.1.2-30-g58a77c1-x86-64.appimage

```
./patternpaint-git2.1.2-30-g58a77c1-x86-64.appimage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
Reinstalling the application may fix this problem.
Aborted
```

**Comment by cibomahto** [comment]
Closing this for now- would you like me to open an issue with linuxdeployqt? It seems there is already one about  -libpath not being functional:
https://github.com/probonopd/linuxdeployqt/issues/51

**Comment by probonopd** [comment]
Is your problem resolved? Also check https://github.com/probonopd/linuxdeployqt/issues/2#issuecomment-244804480

**Comment by cibomahto** [comment]
Yes, it's resolved- i'm just manually copying in the library before running linuxdeployqt, as specified above. It didn't work initially, because I ran into a second problem by removing qmake from the path.

Previously, I was sourcing qt57-env.sh from the PPA to set the QT enviroment variables:
https://github.com/Blinkinlabs/PatternPaint/blob/3e9874ef2be021bebd0e27847c053f4efe972031/.travis.yml

This didn't work on my dev machine, since I am using the Qt installer instead of the PPA, and it does not include an environment script. I am now setting a QTDIR enviroment variable manually before running the distribution script, then specifying the full location of the build tools when required, to avoid setting PATH:
https://github.com/Blinkinlabs/PatternPaint/blob/79ba19f9e4ac46cec8070bae819b48666459e549/.travis.yml
https://github.com/Blinkinlabs/PatternPaint/blob/79ba19f9e4ac46cec8070bae819b48666459e549/dist_linux.sh

Running linuxdeployqt this way (where LINUXDEPLOYQT is the full path to linuxdeployqt) with a path override works:

```
PATH=${QTDIR}/bin:${PATH} ${LINUXDEPLOYQT} app/release/PatternPaint -bundle-non-qt-libs
PATH=${QTDIR}/bin:${PATH} ${LINUXDEPLOYQT} app/release/PatternPaint -appimage
```

It's probably a silly distinction- if it's not recommended to do it this way, I'm happy to improve my implementation.

The current error appears to be a different issue with travis not being able to find the PPA. The build worked fine some hours ago:
https://travis-ci.org/Blinkinlabs/PatternPaint/builds/194180892

**Comment by probonopd** [comment]
Thanks for your clarification @cibomahto and glad you got it working.
