### ISSUE TITLE
Support alternate firmware with RC input

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#176]
As provided by Nightflyer88:
http://forums.blinkinlabs.com/index.php?p=/discussion/398/building-a-pattern-paint-release-not-work

The goal is to have a mechanism to support alternate firmware versions in PatternPaint. Should be fairly straightforward to make a profile class for PatternPaint, that chooses different base firmware. Will be less straightforward to provide support, etc, which suggests that the mechanism should allow an external config file to be loaded, along with the requisite hex files.

[BlinkyTapeRC.zip](https://github.com/Blinkinlabs/PatternPaint/files/714560/BlinkyTapeRC.zip)

**Comment by nightflyer88** [comment]
So I have extended PatternPaint with a possibility to import third-party firmware.

To import a new firmware go to Tools> Firmware manager
Click "add" and select the folder with the hex file.

A folder with the new firmware is now created under Documents/Pattern Paint/Firmware. For an optional firmware description, a README.md file can be created in the firmware folder.
The hex file must have the same name as the folder.

To select the firmware for BlinkyTape upload, go to Tools> scene configuration ..

Only tested on  on MAC OSX.

https://github.com/nightflyer88/PatternPaint

<img width="991" alt="bildschirmfoto 2017-01-28 um 18 40 09" src="https://cloud.githubusercontent.com/assets/25297444/22398461/4c15dda0-e589-11e6-9c60-b05617ced52a.png">

<img width="993" alt="bildschirmfoto 2017-01-28 um 18 42 14" src="https://cloud.githubusercontent.com/assets/25297444/22398481/897c2172-e589-11e6-90ef-2f76d602bf2b.png">

**Comment by cibomahto** [comment]
Very cool! I created a new branch with these changes:
https://github.com/Blinkinlabs/patternpaint/tree/hexloader

However it would be better if you can create a pull request for it, so you get proper credit in the git history:https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Would you mind creating one for this specific part (not including the next two features you worked on)? Otherwise, I can pull it in manually.

**Comment by nightflyer88** [comment]
All right, I have created a pull request, with the two bug fixes. The firmware manager was now also tested with windows, and works very well.

With the blinky exporter I have still the firmware name and percentage memory usage integrated.

**Comment by nightflyer88** [comment]
Should be done. Can be closed by me.

**Comment by cibomahto** [comment]
Yes- it's in the 2.1.4 release, too!
