### ISSUE TITLE
Check for oversized patterns missing

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#177]
Was removed somewhere in the scramble to fix the upload bugs. Urgent!

**Comment by nightflyer88** [comment]
Fixed ! There is now a error message if the Firmware + Patterndata is larger than the available memory size. The upload is then not executed and the bootloader is not damaged.

See here: https://github.com/nightflyer88/PatternPaint

**Comment by cibomahto** [comment]
The specific commit is here:
https://github.com/Blinkinlabs/PatternPaint/pull/179/commits/3cdd7aea4df970aa69379acc63eb6530279ca4c6

**Comment by cibomahto** [comment]
Pulled it in:
https://github.com/Blinkinlabs/PatternPaint/commit/c2bc032d1de8720e42d81d92c1fd8b4feb8fcbd1

This  is effective, however it's a little fragile- it depends on all of the code above it to be correct- for instance, if the pattern data start address is set near the end of flash, leaving a gap between the program data and it, then this could still report the size being ok, but still result in an upload that doesn't fit in memory. Still, it's very similar to what we had before, so lets start with that.

i'd like to implement a more solid memory map that enforces size/alignment/overlap issues with the firmware- there's the beginning of a class for that here:
https://github.com/Blinkinlabs/PatternPaint/blob/master/src/libblinky/memorysection.cpp

The idea would be to have blinkytapeuploaddata build a MemoryMap object to pass back to the blinkytapeuploader, enforcing the size and overlap tests as the object is built.
