### ISSUE TITLE
Add unit tests for firmwareimport

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#181]
Unit tests need to be added to libblinky-test to cover the firmwareimport features. This should include things like
-Pass an invalid filename to the loader and check it returns the right response
-pass hex data with garbled lines (too little data on a line, address sections that overwrite each other, address sections that are non-contiguous, CRC check invalid) to demonstrate that the importer is robust
-pass hex data with correct lines to show that data is extracted from them as expected

This is probably best accomplished by rewriting the firmwareimport features a bit.

**Comment by nightflyer88** [comment]
I think after the rewrite should now the firmwareRead function be robust.

**Comment by cibomahto** [comment]
The rewrite looks pretty solid.

This issue is actually about adding unit tests. For example, take a look at this one that tests some simple byte array conversion functions:
https://github.com/Blinkinlabs/PatternPaint/blob/master/src/libblinky-test/bytearrayhelperstests.cpp

The purpose of this is to make it possible to keep maintaining the project, and to force a design style where different features are separated into small pieces with clear functions.

The tests should cover any potential edge cases (sending 0 bytes of data, normal amounts, too much, etc). that simulate different good and bad inputs to the function to cover as many different inputs to it as possible. It also helps when rewriting sections of code, since you have a set of reference inputs and outputs that a new version is expected to produce.

The tests should also be placed in the libblinky-test main executable:
https://github.com/Blinkinlabs/PatternPaint/blob/master/src/libblinky-test/main.cpp

so that they will be run whenever a distribution is built- that way if any bugs in the code that have test cases, they will be automatically tested and reported.

We're using QTest to do the testing, since it's built into Qt:
https://doc.qt.io/qt-5/qtest-overview.html

I just added this to PatternPaint recently, however the short term goal is to get coverage for all of the functions and classes in libblinky, and a longer term goal is to build automated tests for the GUI as well.

**Comment by cibomahto** [comment]
Largely completed here:
https://github.com/Blinkinlabs/PatternPaint/commit/d063ff3927f711a3521e93fb71ebfadefcb3e75f
