### ISSUE TITLE
zoom function in frame editor

### ISSUE THREAD

**Issue by nightflyer88** [Blinkinlabs/PatternPaint#193]
It would be cool if there was a possibility in the frame editor to zoom. If you have many pixels, it is impossible to draw this exactly.

How could this possibly be done?

In the function I have made a try:

`FrameEditor::setFrameData`
        `float scale = float(size().height())/data.size().height();`
        `this->setMinimumWidth(data.size().width()*scale*2);`
        `this->setMinimumHeight(data.size().height()*scale*2);`

Should zoom by factor 2, but does not work well, since there are problems with the resize window. The frame editor is displayed incorrectly.

**Comment by cibomahto** [comment]
This would be useful! Here's an example of how to scale the window:
https://github.com/Blinkinlabs/PatternPaint/commit/a0897b88c21a52495948edee59e829d6532beadc

The frame editor already contains code to do fractional scaling (since it can adjust to the window size), so the challenges here I think are more about how the interface should work. Some references below

**Comment by cibomahto** [comment]
![photoshop zoom](https://cloud.githubusercontent.com/assets/44493/22851317/c5188f52-f058-11e6-8209-9a6212731206.PNG)
Photoshop has image scaling functions in the 'View' menu:
-Zoom in (ctrl++): zoom in by some amount (..., 12.5%, 16.7%, 25%, 33.3%. 50%, 66.7%, 100%, 200%, 300%, 400%, 500%, 600%, 700%, 800%, 1200%, 1600%, ...)
-Zoom out (ctrl+-): zoom out by some amount (same steps as zoom in)
-Fit on screen (ctrl+0): maximize image inside screen (both horizontally and vertically)
-Fit artboard on screen (not relevant, unless we think of the fixture layout as the artboard- ignore this for now)
-100% (ctrl+1): sets scale to 1:1 (no zoom)
-200%: sets scale to 2:1
-Print Size: (not relevant)

For the mouse (on windows):
-alt+scroll, zooms in/out freely (not by steps),
-ctrl+scroll vertical pans left/right
-shift+scroll vertical pans up/down

Touchpad (on windows):
-alt+pinch, and alt+scroll zoom in/out freely
-shift+swipe pans in both directions
-ctrl+swipe pans in both directions

The touchpad on macOS might work differently, I need to install it on a machine to test.

**Comment by cibomahto** [comment]
![ms paint zoom](https://cloud.githubusercontent.com/assets/44493/22851363/ca67cea8-f05a-11e6-910d-73221ee7ff59.PNG)
MS paint has a ribbon with:
-Zoom in: Zoom in by some amount (12.5, 25, 50, 100, 200, 300, 400, 500, 600, 700, 800)
-Zoom out: Zoom out by some amount (same steps)
-100%: sets scale to 1:1

It also has a slider at the bottom right that selects the same scale

For the mouse:
ctrl+scroll: zoom in and out
scroll: pan up/down

Touchpad:
pinch: zooms in/out
swipe: pans in all directions

**Comment by cibomahto** [comment]
![screen shot 2017-02-11 at 1 29 05 pm](https://cloud.githubusercontent.com/assets/44493/22851492/1bf4a8f6-f05e-11e6-9ff9-e39f81305b41.png)
On macOS, Preview has image scaling functions similar to Photoshop, in the 'View' menu:
-Actual size (cmd+0): zoom 1:1
-Zoom to fit (cmd+9): zooms to show whole image in windows
-Zoom in (cmd++): zooms in by some amount
-Zoom out (cmd+-): zooms out by some amount
-Zoom to selection (cmd+*): zooms to fit the current selection in the window

In addition, the 'actual size' and 'zoom to fit' selections are persistent, so:
-if you manually select 'zoom to fit', then later resize the window, the image will be scaled to fit the max size of the window
-'Zoom to fit' is cleared if any of the manual zoom options are used to resize the image
-However, if you then resize the window manually and it comes close to the image size, the 'zoom to fit' option will be re-enabled, and the image size will snap to the window size.
-manually selecting 'actual size' disables the above snap feature, however if you then resize the window manually, the 'actual size' feature is disabled, and the above snap feature will work again.

Mouse:
scroll wheel: pans up/down
shift+scroll wheel: pans left/right

Touchpad:
pinch: zooms in/out freely
swipe: pans in all directions

**Comment by cibomahto** [comment]
Personally I prefer the behavior of Preview the most; it feels like it mostly just does useful things. The default behavior in PatternPaint right now is similar to the 'zoom to fit' option in Preview, but not in Photoshop since it isn't persistent.

Any other programs that might be good to look at for reference?

**Comment by nightflyer88** [comment]
Looks good, I made a try:
https://github.com/nightflyer88/PatternPaint/tree/test-zoom

There are still problems with the zoom to fit, because it only works if the frameeditor is smaller than the window.

<img width="1113" alt="bildschirmfoto 2017-02-11 um 12 25 40" src="https://cloud.githubusercontent.com/assets/25297444/22853476/858bf1b8-f057-11e6-8ac0-23aca3700a4f.png">

The zoom icons still need to be drawn.

**Comment by cibomahto** [comment]
Added icons (from icons88), and put the actions in the menu bar:
https://github.com/Blinkinlabs/PatternPaint/commit/1b1d4a3b923aae2d051b76aabebb036943a02a1f

**Comment by cibomahto** [comment]
I think the 'zoom to fit' option should be enabled by default (and work continuously), so the behavior is more consistent with the original behavior for PatternPaint.

**Comment by cibomahto** [comment]
It's probably better to redesign this to use the scrollarea to do the zooming:
https://doc.qt.io/qt-5/qtwidgets-widgets-imageviewer-example.html

**Comment by nightflyer88** [comment]
Would be the best solution, but would have to rewrite the whole frameeditor?

I know myself too little with the QLabel, QWidget ...

**Comment by cibomahto** [comment]
I think it would just be some re-arranging of the message handlers for zoom, and then implementing the mouse and gesture events in the scroll area instead of in the frame editor. The main reason is that when zooming using a mouse or gesture, it's way more natural if the zoom happens around the focus of the cursor (or center of the gesture), which means it's actually a zoom+pan operation. My guess is that it's easier to do that from the scroll area, since it keeps the state for the active scroll region.

But that's an enhancement to the zoom feature, so we can maybe make that a separate issue and go with this implementation for now.

**Comment by nightflyer88** [comment]
So have made a few attempts. The problem with the scrollArea is that the image is not rendered at the zoom. The same with QPainter painter.scale()

Look at this, I think that is still the better solution:
https://github.com/nightflyer88/PatternPaint/tree/scaling

**Comment by cibomahto** [comment]
Fully implemented as of here:
https://github.com/Blinkinlabs/PatternPaint/commit/45fd30386225b155c2ced57cd15e6550e8a29ff3
