### ISSUE TITLE
qtcreator: No executable specified

### ISSUE THREAD

**Issue by gringer** [Blinkinlabs/PatternPaint#215]
I'm trying to compile PatternPaint on my Debian box so that I can run it (the packaged version was giving me a segmentation fault). I've finally got it to compile by installing the Debian packages `qtcreator` [v 4.6.0-2] and `libqt5serialport5-dev` [v 5.10.1-2], but the 'run' button from within qtcreator doesn't work (it reports `Starting... No executable specified`).

I'd just like to point out that this is my second attempt at using qtcreator, and the first project that I've been able to successfully compile (in this case, with no change to the provided code), so I'm a little shocked to have got this far already.

**Comment by cibomahto** [comment]
Can you try using the official Qt release:
https://www.qt.io/download-thank-you?os=linux
https://www.qt.io/download-thank-you?os=linux32

My guess would be this is a configuration issue with the Debian packages, so it'd be interesting to test if the qt-provided version is functional, and work back from there.

**Comment by cibomahto** [comment]
ok, glad its working!
