### ISSUE TITLE
Light painting mode

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#48]
As suggested by teaelixer on the forums:
http://forums.blinkinlabs.com/index.php?p=/discussion/120/blinky-tape-with-8-bit-graphics

I am happy to be able to make these pictures, but it would be "cherry on top" if there was a timer display or how long the animation will take and a hotkey starter button (any dedicated key on the keyboard) that will start/end the animation. Holding down the button will allow it to loop animation until release.

Lastly, I would love to take this to the next level with making a series of pictures into an animation. At the moment I haven't found an efficient way to paint yet...

**Comment by MAUIMACMAN** [comment]
I found a great way to control the start and stop of the animation of the BT. I bought a MiniUSB cable with an inline On-OFF switch. works like a charm!   Something like this would work too:  https://www.adafruit.com/products/1620

**Comment by cibomahto** [comment]
Cool! You might want to start a new discussion topic over in the forum about this- i don't think too many people are searching on this page.
