### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by fovea1959** [Blinkinlabs/PatternPaint#50]
Having trouble building on Ubuntu: can't get the QtSerialPort library to get picked up.

Downloaded the library, did a command line install (as root). Still getting

QTSerialPort: no such file or directory 

in blinkytape.h. 

Where do I go to get instructions on setting up a build environment for QT4 with the proper prerequisites?

**Comment by cibomahto** [comment]
Fixed a couple of small issues in 7429db0. It seems to be building fine for m e in Ubuntu 14.4, using the qtcreator 3.0.1-0ubuntu4 package: 
http://packages.ubuntu.com/source/trusty/qtcreator

If there are any other bugs please report them as new issues and we'll try to get them solved.
