### ISSUE TITLE
AnimationEditor doesn't resize correctly after Edit->Resize Pattern called

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#54]
Should resize the window and update scroll bars, etc. The workaround right now is to manually resize the window

**Comment by a-pavlov** [comment]
I made final fix for this problem - direct scroll bar resize after each pattern size change. It is hack, but  it solves problem. I've tried to make "clean" solution like in qt examples, but it means I have to rewrite too many things, so I decided use hack and do not waste time. Please, review result.

**Comment by cibomahto** [comment]
Ok, triggering the scroll bar to resize itself seems to handle the issue.
