### ISSUE TITLE
Border misalignment on some drawing cells

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#58]
This happens at some (but not all) combinations of zoom on both OS X and Windows.
![screen shot 2015-03-28 at 3 20 44 pm](https://cloud.githubusercontent.com/assets/44493/6880161/494b5768-d55e-11e4-8455-a35464dd34c7.png)

**Comment by a-pavlov** [comment]
This is old problem and it happens because of misalignment between scaled small image for tape and originally large image with grid on some arbitrary scale. I made scale factor discrete - changes on 1 each time. Please, review changes and if new behaviour is satisfactory close ticket.

**Comment by cibomahto** [comment]
Yes, it's an old problem from when scaling was first introduced.

For usability, it needs to have a floating scale- doing integer steps doesn't provide a smooth experience for resizing the window.

**Comment by a-pavlov** [comment]
I made ten times more precisely scaling - it is smoother than previous variant and still doesn't have misalignment effect. Please check it.

**Comment by cibomahto** [comment]
Nice, that is cleaner. It seems like it still has some misalignment, though, just reducing the problem. Here's a screenshot of the effect, running from commit 68e022130b

![screen shot 2015-04-07 at 4 08 54 pm](https://cloud.githubusercontent.com/assets/44493/7019260/ace16d46-dd40-11e4-9eb4-dd8bf5ef1cb2.png)

**Comment by a-pavlov** [comment]
It is tricky problem and I suspect it hasn't solution in drawing image and grid in different scales. So now I can suggest this temp fix which simply reduces problem.

**Comment by a-pavlov** [comment]
In slideshow branch I changed coefficient to reduce problem more. Please, check it.

**Comment by cibomahto** [comment]
I'll accept this so we can move on, and open a new issue for fixing the underlying problem.
