### ISSUE TITLE
File 'open' doesn't prompt for save if previous image has been modified

### ISSUE THREAD

**Issue by cibomahto** [Blinkinlabs/PatternPaint#60]
Should have the same dialog as when exiting the program.

**Comment by a-pavlov** [comment]
Fixed. Combination with undo command in progress.

**Comment by cibomahto** [comment]
Ok, technically this is a working solution. Please use the save dialog style from this commit:

https://github.com/Blinkinlabs/PatternPaint/commit/c99443bcf5ab20d647cb005556f9d341dbc47bde

The dialog boxes need to be consistent and default to the OS display style. It's annoying in OS X and Windows when the button order in dialogs is not consistent with the system style, and QT provides some means for handling this automatically.

**Comment by a-pavlov** [comment]
Original dialog has been restored. For open dialog I replaces Discard button to Open. Should I correct this button to something more appropriate?

**Comment by cibomahto** [comment]
Looks good. Yes, discard should still be the same label. I'll make that change.
